# Generated by Django 4.2.3 on 2023-07-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='date_finish',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='archive',
            name='date_start',
            field=models.CharField(max_length=10),
        ),
    ]
