# Generated by Django 4.2.3 on 2023-07-06 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_archive_date_finish_alter_archive_date_start'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archive',
        ),
    ]
