# Generated by Django 4.2.3 on 2023-07-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_archive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archive',
        ),
    ]
